name: Restrict PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  close_unauthorized_pr:
    if: github.actor != 'donghao0210'
    runs-on: ubuntu-latest

    steps:
      - name: Close unauthorized PR to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr close ${{ github.event.pull_request.number }} -c "Only authorized users can open pull requests to the main branch."